// Reads .env.local and writes electron/secrets.cjs so credentials are
// available at runtime in the packaged app (process.env is empty there).
// Run this before electron-builder — the output file is gitignored.

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const envPath = join(ROOT, '.env.local')

if (!existsSync(envPath)) {
  console.error('bake-secrets: .env.local not found — skipping')
  process.exit(0)
}

const env = {}
for (const line of readFileSync(envPath, 'utf8').split('\n')) {
  const trimmed = line.trim()
  if (!trimmed || trimmed.startsWith('#')) continue
  const eq = trimmed.indexOf('=')
  if (eq < 1) continue
  const key = trimmed.slice(0, eq).trim()
  const val = trimmed.slice(eq + 1).trim()
  if (key && val) env[key] = val
}

const out = join(ROOT, 'electron', 'secrets.cjs')
writeFileSync(out, `// auto-generated by scripts/bake-secrets.mjs — do not edit or commit\nmodule.exports = ${JSON.stringify(env, null, 2)}\n`)
console.log('bake-secrets: wrote electron/secrets.cjs')
